### PR TITLE
Day 3, bro!

### PR DESCRIPTION
**Pull request by bayleedev**

### CODE REVIEW

**Comment by afaur** [comment]
Did you even test this? This doesn't work.
screen shot 2016-12-18 at 9 56 48 pm

**Comment by bayleedev** [comment]
Merge conflict. Apparently the thing I cloned and the thing you had were different. My `img {}` css got stripped out [:

See bdbe853ec5d42aae5cc819f6f82159f5f877e4d1

**Comment by afaur** [comment]
Still not correct... Did you not notice how when you first open the page your image is super blurry and the slider for blur is all the way down?
screen shot 2016-12-18 at 10 57 08 pm

**Comment by afaur** [comment]
Also, I completed this already in a different way.  Going to close this PR.

**Comment by afaur** [comment]
Why do you set an initial value for the css properties in the style section?  I think the point was that the controls should be bound to the css alterations directly.

**Comment by bayleedev** [comment]
The default values changed, who cares?

**Comment by bayleedev** [comment]
I had merge conflicts because you have an out of date master.

**Pull request closed without merging**
